site_name: Frosch
site_url: https://example.com/

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Features:
    - Exception Printing: exception_printing.md
  - Configuration:
    - Themes: themes.md
    - Notifications: notifications.md
  - About: about.md

theme:
  name: "material"
  palette:
    - scheme: default
      primary: "teal"    
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: "teal"    
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
- search
- mkdocstrings
